name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        export TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag pknw1/flask_cards:${TIMESTAMP}
        docker push pknw1/flask_cards:${TIMESTAMP}
        docker build . --file Dockerfile --tag pknw1/flask_cards:latest

